export const variants = {
  tag: {
    h1: "text-[40px] font-bold leading-13 hyphens-auto sm:hyphens-none font-heading",
    h2: "text-[32px] font-bold hyphens-auto sm:hyphens-none font-heading",
    h3: "text-2xl font-bold hyphens-auto sm:hyphens-none font-heading",
    h4: "text-xl font-bold hyphens-auto sm:hyphens-none font-heading",
    h5: "text-base font-bold font-heading",
    h6: "text-xs font-bold font-heading",
    p: "text-sm",
    span: "text-sm",
  },
  size: {
    xs: "text-xs",
    sm: "text-sm",
    base: "text-base",
    lg: "text-lg",
    xl: "text-xl",
  },
  weight: {
    bold: "font-bold",
    "semi-bold": "font-semibold",
    medium: "font-medium",
    normal: "font-normal",
    light: "font-light",
  },
  color: {
    primary: "text-primary",
    secondary: "text-secondary-foreground",
    foreground: "text-foreground",
    muted: "text-muted-foreground",
    destructive: "text-destructive",
    white: "text-white",
    "gray-950": "text-gray-950",
    "gray-900": "text-gray-900",
    "gray-800": "text-gray-800",
    "gray-700": "text-gray-700",
    "gray-600": "text-gray-600",
    "gray-500": "text-gray-500",
    "gray-400": "text-gray-400",
    "gray-300": "text-gray-300",
    "gray-200": "text-gray-200",
    "gray-100": "text-gray-100",
    "gray-50": "text-gray-50",
  },
  font: {
    sans: "font-sans",
    heading: "font-heading",
  },
  align: {
    left: "text-left",
    center: "text-center",
    right: "text-right",
  },
  underline: {
    true: "underline",
    false: "",
  },
};
